# Generated by Django 2.2.6 on 2019-11-09 07:56

import common.base_models
from decimal import Decimal
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_center', '0005_auto_20191109_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_info', common.base_models.MYJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('deposit_amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='充值门槛, 单位为元', max_digits=65, verbose_name='Deposit Amount')),
                ('cash_back_amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='返现多少元', max_digits=65, verbose_name='Deposit cash back amount')),
                ('cash_back_expired_day', models.PositiveSmallIntegerField(help_text='返现后多少天可以提现', verbose_name='cash back expired to withdraw')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Deposit Cash Back',
                'verbose_name_plural': 'Deposit Cash Back',
            },
        ),
        migrations.CreateModel(
            name='PayCashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_info', common.base_models.MYJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Pay Cash Back Name')),
                ('start_at', models.DateTimeField(help_text='活动开始时间', verbose_name='Start Time')),
                ('end_at', models.DateTimeField(help_text='活动结束时间', verbose_name='End Time')),
                ('total_paied_amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='活动期间累计消费门槛，单位为元', max_digits=65, verbose_name='PayCashBack Amount')),
                ('cash_back_amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='累积消费到达门槛后，一次性返现数量', max_digits=65, verbose_name='PayCashBack Amount')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Pay Cash Back',
                'verbose_name_plural': 'Pay Cash Back',
            },
        ),
        migrations.CreateModel(
            name='PayCashBackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pay_cash_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cash_back.PayCashBack')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_center.ShopUser')),
            ],
            options={
                'verbose_name': 'Pay Cash Back Record',
                'verbose_name_plural': 'Pay Cash Back Record',
                'unique_together': {('pay_cash_back', 'shop_user')},
            },
        ),
    ]
