# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1-slim

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
						- pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
						- pip-packages-v1-{{ .Branch }}-
						- pip-packages-v1-

      - run:
          name: install dependencies
          command: |
					  pipenv install --deploy --system

      - save_cache:
					paths:
						- ~/.local/share/virtualenvs/venv 
					key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
						pipenv shell
            python manage.py test
