# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1
      - image: circleci/redis:5.0.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: bshop
          POSTGRES_PASSWORD: bshop
          POSTGRES_DB: bshopdb_test
          DB_PASS: bshop
          DB_USER: bshop
          DB_NAME: bshopdb_test
          ENABLE_COVERAGE: true

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pip-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v3-{{ .Branch }}-
            - pip-packages-v3-

      - run:
          name: install dependencies
          command: |
            pipenv install --deploy

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/
          key: pip-packages-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            cd bshop 
            pipenv run python manage.py test
