# Generated by Django 2.2.6 on 2019-10-25 06:38

import common.base_models
from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quota', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
