# Generated by Django 2.2.6 on 2019-10-03 02:48

import common.base_models
from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_center', '0002_auto_20191003_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65)),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_funds', to='user_center.ShopUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65)),
                ('from_fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_from', to='wallet.Fund')),
                ('to_fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_to', to='wallet.Fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
