# Generated by Django 2.2.6 on 2019-10-25 07:58

import common.base_models
from decimal import Decimal
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("user_center", "0002_auto_20191003_0248")]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "extra_info",
                    common.base_models.MYJSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "cash",
                    common.base_models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=65
                    ),
                ),
                (
                    "shop_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_funds",
                        to="user_center.ShopUser",
                    ),
                ),
                ("currency", models.CharField(default="CNY", max_length=8)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="FundTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "extra_info",
                    common.base_models.MYJSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ADMIN_REQUIRED", "ADMIN_REQUIRED"),
                            ("ADMIN_DENIED", "ADMIN_DENIED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    common.base_models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=65
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WITHDRAW", "WITHDRAW"),
                            ("DEPOSIT", "DEPOSIT"),
                            ("CASHBACK", "CASHBACK"),
                            ("TRANSFER", "TRANSFER"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=128, null=True)),
                ("order_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "from_fund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_as_from",
                        to="wallet.Fund",
                    ),
                ),
                (
                    "to_fund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_as_to",
                        to="wallet.Fund",
                    ),
                ),
            ],
            options={"abstract": False, "unique_together": {("type", "order_id")}},
        ),
        migrations.CreateModel(
            name="FundAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "extra_info",
                    common.base_models.MYJSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    common.base_models.MYJSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_actions",
                        to="wallet.Fund",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.FundTransfer",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="HoldFund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "extra_info",
                    common.base_models.MYJSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    common.base_models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=65
                    ),
                ),
                ("expired_at", models.DateTimeField()),
                (
                    "order_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hold_funds",
                        to="wallet.Fund",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
