# Generated by Django 2.2.6 on 2019-11-09 07:56

import common.base_models
from decimal import Decimal
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0005_auto_20191109_0304'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'Fund', 'verbose_name_plural': 'Funds'},
        ),
        migrations.AlterModelOptions(
            name='fundaction',
            options={'verbose_name': 'Fund action', 'verbose_name_plural': 'Fund actions'},
        ),
        migrations.AlterModelOptions(
            name='fundtransfer',
            options={'verbose_name': 'Fund transfer', 'verbose_name_plural': 'Fund transfers'},
        ),
        migrations.AlterModelOptions(
            name='holdfund',
            options={'verbose_name': 'Hold fund', 'verbose_name_plural': 'Hold funds'},
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='from_shop_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_center.ShopUser'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='cash',
            field=common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65, verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='currency',
            field=models.CharField(default='CNY', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='fundaction',
            name='balance',
            field=common.base_models.MYJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Transfer Note'),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='status',
            field=models.CharField(choices=[('ADMIN_REQUIRED', 'ADMIN_REQUIRED'), ('ADMIN_DENIED', 'ADMIN_DENIED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='SUCCESS', max_length=16, verbose_name='Transfer status'),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='type',
            field=models.CharField(blank=True, choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT'), ('TRANSFER', 'TRANSFER'), ('PAY', 'PAY'), ('PAY_CASHBACK', 'PAY_CASHBACK'), ('DEPOSIT_CASHBACK', 'DEPOSIT_CASHBACK')], max_length=16, null=True, verbose_name='Transfer Type'),
        ),
        migrations.AlterField(
            model_name='holdfund',
            name='amount',
            field=common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='holdfund',
            name='expired_at',
            field=models.DateTimeField(verbose_name='Expired At'),
        ),
    ]
