# Generated by Django 2.2.6 on 2019-10-21 09:25

import common.base_models
from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_fundaction_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', common.base_models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=65)),
                ('expired_at', models.DateTimeField()),
                ('order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_funds', to='wallet.Fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
