# Generated by Django 2.2.6 on 2019-10-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
