# Generated by Django 2.2.6 on 2019-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_auto_20191003_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='payment_password',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment password'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Is vendor'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Vendor Name'),
        ),
    ]
