# Generated by Django 2.2.6 on 2019-10-24 03:51

import common.base_models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_auto_20191005_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='extra_info',
            field=common.base_models.MYJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
